M48
; DRILL file {KiCad 6.0.8-1.fc36} date Sat 05 Nov 2022 02:52:56 AM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-05T02:52:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-1.fc36
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X109.412Y-78.74
X109.412Y-95.25
X175.452Y-78.74
T0
M30
